# DE Utils

In [1]:
import numpy as np
import sys
import os
sys.path.insert(0, os.path.join(os.getcwd(), '..', 'src'))
from utils import de
from benchmark.simple import rosenbrock, rastrigin

## Initialize population

In [2]:
pop = de.populate(
    size = 5,
    min = -5,
    max = 5,
    dimensions = 2
)

print(pop)

[[ 2.58063307  4.68579546 -3.30741995  3.39386604  1.46757085]
 [ 1.50219587 -2.8557604  -2.16399528  3.37662826  1.09429971]]


## Mutate population

In [3]:
mutants = de.mutate(population = pop, factor = 0.5)
print(mutants)

[[ 4.96812847  5.33176017 -3.86395106  3.80048253  2.43071845]
 [ 3.13134337 -5.97195473 -2.36794336  4.31384446  2.23546399]]


## Crossover

In [4]:
trials = de.cross(population = pop, mutants = mutants, rate = 0.25)
print(trials)

[[ 4.96812847  5.33176017 -3.86395106  3.80048253  2.43071845]
 [ 3.13134337 -5.97195473 -2.36794336  3.37662826  2.23546399]]


## Selection

In [5]:
generation = de.select(population = pop, trials = trials, fitness = rosenbrock)
print(generation)

[[ 2.58063307  4.68579546 -3.30741995  3.39386604  1.46757085]
 [ 1.50219587 -2.8557604  -2.16399528  3.37662826  1.09429971]]


## Optimization

### Rosenbrock

In [6]:
NP = 20
D = 50
min = -10
max = 10
F = 0.25
CR = 0.25
fitness = rosenbrock
n = 250

In [7]:
best = de.optimize(
    populationSize = NP,
    dimentions = D,
    min = min,
    max = max,
    mutationFactor = F,
    crossingRate = CR,
    fitness = fitness,
    generations = n,
    controlDiversity = False
)

print(rosenbrock(best))

0.009158849545871156


In [8]:
best = de.optimize(
    populationSize = NP,
    dimentions = D,
    min = min,
    max = max,
    mutationFactor = F,
    crossingRate = CR,
    fitness = fitness,
    generations = n,
    controlDiversity = True
)

print(rosenbrock(best))

0.01712698835063424


### Rastrigin

In [9]:
NP = 100
D = 100
min = -10
max = 10
F = 0.25
CR = 0.25
fitness = rastrigin
n = 1500

In [10]:
best = de.optimize(
    populationSize = NP,
    dimentions = D,
    min = min,
    max = max,
    mutationFactor = F,
    crossingRate = CR,
    fitness = fitness,
    generations = n,
    controlDiversity = False
)

print(rastrigin(best))

936.9561498867612


In [11]:
best = de.optimize(
    populationSize = NP,
    dimentions = D,
    min = min,
    max = max,
    mutationFactor = F,
    crossingRate = CR,
    fitness = fitness,
    generations = n,
    controlDiversity = True
)

print(rastrigin(best))


914.414860952465
