# DE Utils

In [1]:
import numpy as np
import sys
import os
sys.path.insert(0, os.path.join(os.getcwd(), '..', 'src'))
from utils import de
from benchmark.simple import rosenbrock, rastrigin

## Initialize population

In [2]:
pop = de.populate(
    size = 5,
    min = -5,
    max = 5,
    dimensions = 2
)

print(pop)

[[ 3.6160174   4.38806243  1.0649642  -2.24662635 -3.79310056]
 [ 3.97053836  0.77378613 -2.7542938  -4.49009413 -0.32211992]]


## Mutate population

In [3]:
mutants = de.mutate(population = pop, factor = 0.5)
print(mutants)

[[ 0.68469553  6.0438577   2.72075947 -3.01986345 -6.22213294]
 [-0.25977788  1.64168629 -1.88639364 -2.40610702  0.89396703]]


## Crossover

In [4]:
trials = de.cross(population = pop, mutants = mutants, rate = 0.25)
print(trials)

[[ 0.68469553  6.0438577   1.0649642  -2.24662635 -6.22213294]
 [-0.25977788  1.64168629 -1.88639364 -2.40610702 -0.32211992]]


## Selection

In [5]:
generation = de.select(population = pop, trials = trials, fitness = rosenbrock)
print(generation)

[[ 0.68469553  4.38806243  1.0649642  -2.24662635 -3.79310056]
 [-0.25977788  0.77378613 -1.88639364 -2.40610702 -0.32211992]]


## Optimization

In [6]:
best = de.optimize(
    populationSize = 20,
    dimentions = 2,
    min = -10,
    max = 10,
    mutationFactor = 0.25,
    crossingRate = 0.25,
    fitness = rosenbrock,
    generations = 5000,
)

print(best)

[1. 1.]


In [7]:
best = de.optimize(
    populationSize = 20,
    dimentions = 2,
    min = -10,
    max = 10,
    mutationFactor = 0.25,
    crossingRate = 0.25,
    fitness = rastrigin,
    generations = 5000,
)

print(best)

[ 8.76281357e-10 -2.08401840e-09]
