In [1]:
import numpy as np
import sys
import os
sys.path.insert(0, os.path.join(os.getcwd(), '..', 'src'))
from utils import de
from benchmark.simple import rosenbrock

In [2]:
pop = de.populate(
    size = 5,
    min = -5,
    max = 5,
    dimensions = 2
)

print(pop)

[[-2.79634253  4.40412018 -0.57357746 -0.96213331 -1.35035713]
 [-1.9339756   1.82320796 -4.53969039  4.5665814  -0.84454448]]


In [3]:
mutants = de.mutate(population = pop, factor = 0.5)
print(mutants)

[[-1.87923792  1.72099344 -0.76785538 -0.0450287  -2.26746173]
 [ 1.3163029   3.19489468  0.0134455   7.81685989 -4.09482298]]


In [4]:
trials = de.cross(population = pop, mutants = mutants, rate = 0.25)
print(trials)

[[-1.87923792  1.72099344 -0.76785538 -0.96213331 -1.35035713]
 [ 1.3163029   3.19489468 -4.53969039  7.81685989 -0.84454448]]


In [5]:
generation = de.select(population = pop, trials = trials, fitness = rosenbrock)
print(generation)

[[-1.87923792  1.72099344 -0.57357746 -0.96213331 -1.35035713]
 [ 1.3163029   3.19489468 -4.53969039  4.5665814  -0.84454448]]


In [6]:
best = de.optimize(
    populationSize = 20,
    dimentions = 2,
    min = -10,
    max = 10,
    mutationFactor = 0.25,
    crossingRate = 0.25,
    fitness = rosenbrock,
    generations = 5000,
)

print(best)

[1. 1.]
