# DE Utils

In [41]:
import numpy as np
import sys
import os
sys.path.insert(0, os.path.join(os.getcwd(), '..', 'src'))
from utils import de
from benchmark.simple import rosenbrock, rastrigin, shubert

## Functions

### Initialize

In [6]:
pop = de.populate(
    size = 5,
    boundaries = [(-10,10), (-10,10)]
)

pop2 = de.populate(
    size = 5,
    boundaries = [(-10,10)],
    dimensions = 2
)

print(pop.shape)
print(pop2.shape)

print(pop)

(2, 5)
(2, 5)
[[ 1.35789976 -1.98379183  9.87077112  5.58319789  9.12101167]
 [ 6.2952116  -0.83211792  2.58054659 -3.7151826   1.10650595]]


### Mutate

In [ ]:
mutants = de.mutate(population = pop, factor = 0.5)
print(mutants)

### Crossover

In [ ]:
trials = de.cross(population = pop, mutants = mutants, rate = 0.25)
print(trials)

### Selection

In [ ]:
generation = de.select(population = pop, trials = trials, fitness = rosenbrock)
print(generation)

## Optimization

### Rosenbrock

In [8]:
best = de.optimize(
    populationSize = 20,
    boundaries = [(-10,10), (-10,10)],
    mutationFactor = 0.5,
    crossingRate = 0.5,
    fitness = rosenbrock,
    generations = 1500
)

print(best)
print(rosenbrock(best))

[1. 1.]
7.888609052210118e-31


### Rastrigin

In [20]:
best = de.optimize(
    populationSize = 20,
    boundaries = [(-10,10)],
    dimensions = 200,
    mutationFactor = 0.5,
    crossingRate = 0.5,
    fitness = rastrigin,
    generations = 1500
)

print(best)
print(rastrigin(best))

[ 1.15696937e+00  7.73737839e-01  3.02664216e-01  5.73610511e-01
 -3.53162262e-02 -9.31508024e-02  2.32111575e+00  1.00695526e-01
 -7.10820310e-01 -1.97731594e+00 -1.13774418e+00  9.57724791e-01
 -2.86455105e-01  2.00244987e+00 -1.39369499e+00 -3.31995792e+00
 -4.31894786e-01 -1.91597401e+00 -6.69658788e-01 -2.09698960e+00
 -2.19771635e-01 -3.58195360e-03  3.61525617e+00  9.94828475e-01
  3.02133487e+00 -9.90461299e-01  1.18049949e+00 -8.57690104e-01
  1.22446834e+00 -8.08413219e-01  9.93726884e-01 -1.02391071e+00
  7.53223054e-01 -1.09408556e-03  1.62148804e-01 -2.13552704e+00
 -2.87831388e+00  1.76123224e+00 -6.97373555e-02  4.86778983e-01
  1.46636549e+00 -2.05217623e+00  1.11429851e-02 -7.87046456e-02
  1.91408868e+00 -2.24346287e-01  5.56882444e-01  3.44856118e-02
  3.15210703e-01  1.61649380e+00  1.29681686e+00  1.92889168e+00
  5.09999555e-01 -1.06450072e-01 -1.10853191e+00 -1.49932040e+00
  2.37283932e-01  2.49556160e+00 -8.26695664e-01 -1.46370373e+00
  1.34820536e+00 -1.08919

### Shubert

In [ ]:
best = de.optimize(
    populationSize = 20,
    boundaries = [(-10,10), (-10,10)],
    mutationFactor = 0.5,
    crossingRate = 0.5,
    fitness = shubert,
    generations = 1500
)

print(best)
print(shubert(best))

In [24]:
boundaries = np.array([(-10,10)]*3)
print(boundaries)

[[-10  10]
 [-10  10]
 [-10  10]]


In [38]:
for d in range(boundaries.shape[0]):
    print(np.linspace(boundaries[d,0],boundaries[d,1],groups+1))

[-10.  -5.   0.   5.  10.]
[-10.  -5.   0.   5.  10.]
[-10.  -5.   0.   5.  10.]
