# DE Utils

In [1]:
import numpy as np
import sys
import os
sys.path.insert(0, os.path.join(os.getcwd(), '..', 'src'))
from utils import de
from benchmark.simple import rosenbrock, rastrigin, shubert

## Functions

### Initialize

In [2]:
pop = de.populate(
    size = 5,
    boundaries = [(-10,10), (-10,10)]
)

print(pop)

[[-1.72427182 -1.7164983  -9.04622636  2.26771926  8.88258361]
 [ 4.807607    3.2504122   8.97163553  1.20871709 -9.75733716]]


### Mutate

In [3]:
mutants = de.mutate(population = pop, factor = 0.5)
print(mutants)

[[-1.72815858 -7.37347111 -3.7466854  -1.39714477  5.21771958]
 [ 5.5862044   7.13187141  2.46776084  4.06932876 -6.8967255 ]]


### Crossover

In [4]:
trials = de.cross(population = pop, mutants = mutants, rate = 0.25)
print(trials)

[[-1.72815858 -1.7164983  -9.04622636  2.26771926  5.21771958]
 [ 5.5862044   7.13187141  2.46776084  4.06932876 -6.8967255 ]]


### Selection

In [5]:
generation = de.select(population = pop, trials = trials, fitness = rosenbrock)
print(generation)

[[-1.72427182 -1.7164983  -9.04622636  2.26771926  5.21771958]
 [ 4.807607    3.2504122   8.97163553  4.06932876 -6.8967255 ]]


## Optimization

### Rosenbrock

In [6]:
best = de.optimize(
    populationSize = 20,
    boundaries = [(-10,10), (-10,10)],
    mutationFactor = 0.5,
    crossingRate = 0.5,
    fitness = rosenbrock,
    generations = 1500
)

print(best)
print(rosenbrock(best))

[1. 1.]
6.7053176943786e-30


### Rastrigin

In [7]:
best = de.optimize(
    populationSize = 20,
    boundaries = [(-10,10), (-10,10)],
    mutationFactor = 0.5,
    crossingRate = 0.5,
    fitness = rastrigin,
    generations = 1500
)

print(best)
print(rastrigin(best))

[-5.41840097e-10 -2.35668399e-09]
0.0


### Shubert

In [8]:
best = de.optimize(
    populationSize = 20,
    boundaries = [(-10,10), (-10,10)],
    mutationFactor = 0.5,
    crossingRate = 0.5,
    fitness = shubert,
    generations = 1500
)

print(best)
print(shubert(best))

[  24.3324201  2337.77006216]
[-186.73090883]
